name: Lighthouse Report on Merge

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Create a new branch to run the build and tests on
      - run: git checkout -b lighthouse

      # Build the project
      - run: npm install && npm run build

      # Start the build server
      - run: npm start

      # Generate the Lighthouse report
      - run: npx unlighthouse-ci --site http://localhost:3000 --reporter json

      # Save the report as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .unlighthouse/ci-result.json
          run: echo "Artifact created"